apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: unifi-config

labels:
  - pairs:
      app: unifi
      managedBy: argocd
      managementCodeGroup: chrismlee42
      managementCodeProject: unifi-config

namespace: unifi

resources:
  - namespace.yaml
  - unifi-mongo-credentials-secret.yaml