apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: unifi-config

labels:
  - pairs:
      app: unifi
      managedBy: argocd
      managementCodeGroup: chrismlee42
      managementCodeProject: unifi-config

namespace: unifi

resources:
  - mongo-init-grant-configmap.yaml
  - namespace.yaml
  - unifi-controller-service.yaml
  #- unifi-controller-statefulset.yaml
  #- unifi-data-persistentvolumeclaim.yaml
  - unifi-db-service.yaml
  - unifi-db-statefulset.yaml
  - unifi-mongo-credentials-secret.yaml
  # - unifi-mongodbcommunity.yaml