apiVersion: v1
kind: Service
metadata:
  name: unifi-controller-tcp
  annotations:
    external-dns.alpha.kubernetes.io/hostname: unifi.service.clee.private.morphacy.net
    lbipam.cilium.io/sharing-key: unifi-controller
spec:
  type: LoadBalancer
  ports:
    - name: https-ui
      port: 8843
      protocol: TCP
      targetPort: 8843
    - name: api
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: http-portal
      port: 8880
      protocol: TCP
      targetPort: 8880
    - name: controller
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: speed-test
      port: 6789
      protocol: TCP
      targetPort: 6789
  selector:
    app: unifi-controller
