apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: unifi-controller
spec:
  selector:
    matchLabels:
      app: unifi-controller
  serviceName: unifi-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: unifi-controller
    spec:
      containers:
        - name: unifi-controller
          image: lscr.io/linuxserver/unifi-network-application:latest
          imagePullPolicy: Always
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            privileged: true
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Etc/UTC"
            - name: MEM_LIMIT
              value: "1024"
            - name: MEM_STARTUP
              value: "1024"
            # Mongo connection
            - name: MONGO_USER
              value: "unifi"
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: unifi-mongo-credentials
                  key: password
            - name: MONGO_HOST
              value: "unifi-db.unifi.svc.cluster.local"
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_DBNAME
              value: "unifi"
            - name: MONGO_AUTHSOURCE
              value: "admin"
          ports:
            - name: unifi-discovery
              containerPort: 10001
              protocol: UDP
            - name: stun
              containerPort: 3478
              protocol: UDP
            - name: syslog
              containerPort: 5514
              protocol: UDP
            - name: https-ui
              containerPort: 8843
              protocol: TCP
            - name: api
              containerPort: 8443
              protocol: TCP
            - name: http-portal
              containerPort: 8880
              protocol: TCP
            - name: controller
              containerPort: 8080
              protocol: TCP
            - name: speed-test
              containerPort: 6789
              protocol: TCP
          volumeMounts:
            - name: unifi-data
              mountPath: /config
      volumes:
        - name: unifi-data
          persistentVolumeClaim:
            claimName: unifi-data
  # volumeClaimTemplates:
  #   - metadata:
  #       name: unifi-data
  #     spec:
  #       accessModes: ["ReadWriteOnce"]
  #       resources:
  #         requests:
  #           storage: 5Gi
