apiVersion: v1
kind: Service
metadata:
  name: unifi-controller-udp
  annotations:
    external-dns.alpha.kubernetes.io/hostname: unifi.service.clee.private.morphacy.net
    lbipam.cilium.io/sharing-key: unifi-controller
spec:
  type: LoadBalancer
  ports:
    - name: unifi-discovery
      port: 10001
      protocol: UDP
      targetPort: 10001
    - name: stun
      port: 3478
      protocol: UDP
      targetPort: 3478
    - name: syslog
      port: 5514
      protocol: UDP
      targetPort: 5514
  selector:
    app: unifi-controller
